database:
    driverClass: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quotedb?autoReconnect=true
    user: root
    password: ${MYSQL_PASSWORD}
    maxWaitForConnection: 10s
    validationQuery: "SELECT 1"
    validationQueryTimeout: 5s
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute
    checkConnectionOnBorrow: true
